<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <PackageId>ZKAccess</PackageId>
    <Description>Cross-platform .NET client for ZKTeco standalone device protocol.</Description>
    <Authors>Vahid Rassouli</Authors>
    <RepositoryUrl>https://github.com/vrassouli/ZKAccess</RepositoryUrl>
  </PropertyGroup>

</Project>
